---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-mysql-service-group16
  namespace: dvwa-mysql-group16
spec:
  selector:
    app: dvwa-mysql
    tier: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
