apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows this list of subjects to use the role-dvwa in
# the namespace ns-dvwa-group16.
kind: RoleBinding
metadata:
  name: rolebinding-web
  namespace: dvwa-mysql-group16
subjects:
- kind: ServiceAccount
  name: dvwa-web-sa
  namespace: dvwa-web-group16
roleRef:
  kind: ClusterRole 
  name: role-web
  apiGroup: rbac.authorization.k8s.io
